// src/vue/src/components/Conversion.vue
<script setup lang="ts">
defineProps<{
  label?: string
  disabled?: boolean
}>()
const emit = defineEmits(['convert'])
</script>
<template>
  <div class="flex flex-col items-center my-8">
    <button @click="$emit('convert')" :disabled="disabled"
      class="bg-blue-700 hover:bg-blue-800 text-white text-3xl px-16 py-8 rounded-2xl shadow-2xl font-extrabold mb-2 transition-colors"
      :class="{ 'opacity-50 cursor-not-allowed': disabled }">
      Convert
    </button>
    <span class="text-lg font-medium text-sky-600">{{ label }}</span>
  </div>
</template>

// src/next-js/app/components/Conversion.tsx
'use client';

export default function Conversion({
  onConvert,
  label = "Big Green Button!",
  disabled = false,
}: {
  onConvert: () => void;
  label?: string;
  disabled?: boolean;
}) {
  return (
    <div className="flex flex-col items-center my-8">
      <button
        onClick={onConvert}
        disabled={disabled}
        className={`bg-green-600 hover:bg-green-700 text-white text-xl px-8 py-4 rounded-lg shadow-lg font-bold mb-2 transition-colors ${disabled ? "opacity-50 cursor-not-allowed" : ""}`}
      >
        Convert
      </button>
      <span className="text-lg font-medium text-green-700">{label}</span>
    </div>
  );
}
